# Generated by Django 6.0.1 on 2026-02-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('link', models.URLField()),
                ('preview', models.CharField(max_length=300)),
                ('icon', models.CharField(max_length=300)),
                ('techstack', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
        ),
    ]
