# Generated by Django 6.0.1 on 2026-02-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='preview',
            new_name='thumbnail',
        ),
    ]
