# Generated by Django 6.0.1 on 2026-02-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience_experiencebullet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencebullet',
            options={},
        ),
        migrations.RemoveField(
            model_name='experiencebullet',
            name='order',
        ),
    ]
