# Generated by Django 6.0.1 on 2026-02-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experiencebullet_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencebullet',
            old_name='text',
            new_name='bullet',
        ),
    ]
