# Generated by Django 6.0.1 on 2026-02-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_text_experiencebullet_bullet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencebullet',
            old_name='bullet',
            new_name='text',
        ),
    ]
