# Generated by Django 6.0.1 on 2026-02-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_rename_bullet_experiencebullet_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Technology',
        ),
    ]
