# Generated by Django 6.0.1 on 2026-02-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_technology_delete_skill_alter_project_techstack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
