# Generated by Django 6.0.1 on 2026-02-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_skill_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category',
        ),
    ]
