# Generated by Django 6.0.1 on 2026-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_resume_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
